import turtle as tk
t=tk.Turtle()
t.speed(1)
wn=tk.Screen()
wn.bgcolor('black')
wn.title("bhavya heart")
t.begin_fill()
t.fillcolor('red')
t.pensize(3)
t.pencolor('red')
t.left(140)
t.forward(180)
t.circle(-90,200)
t.left(120)
t.circle(-90,200)
t.forward(180)
t.end_fill()
t.hideturtle()
tk.exitonclick()