import turtle
pen=turtle.Pen()
pen.forward(300)
pen.left(90)
pen.forward(300)
pen.left(90)
pen.forward(300)
pen.left(90)
pen.forward(300)
pen.left(90)
pen.forward(300)
pen.reset()
for var in range(4):
    pen.forward(300)
    pen.left(90)
pen.reset()
pen.color('red','green')
pen.begin_fill()
pen.circle(100)
pen.end_fill()
pen.up()
pen.backward(500)
pen.forward(250)
pen.backward(50)
pen.down()
pen.color('green','red')
for var in range(4):
    pen.forward(50)
    pen.left(90)
pen.end_fill()
turtle.exitonclick()
